name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    name: Backend Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: excel-nt-db
        ports:
        - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d excel-nt-db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          
    strategy:
      matrix: 
        node-version: [18.x, 20.x]

    env: 
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/excel-nt-db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Run migrations
        working-directory: backend
        run: npm run migrate --if-present

      - name: Build backend
        working-directory: backend
        run: npm run build --if-present

      - name: Test backend
        working-directory: backend
        run: npm test


  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Test frontend
        working-directory: frontend
        run: npm test
